# Generated by Django 3.1.6 on 2021-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='opname',
            field=models.CharField(max_length=100),
        ),
    ]
